# Generated by Django 5.0.13 on 2025-03-30 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_date_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='username'),
        ),
    ]
