# Generated by Django 5.0.13 on 2025-04-10 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0005_dogparent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dogparent',
            options={'verbose_name': 'parent', 'verbose_name_plural': 'parents'},
        ),
    ]
